export const ADD_EVENT = "ADD_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const PERMANENTLY_DELETE_EVENT = "PERMANENTLY_DELETE_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const FETCH_EVENTS = "FETCH_EVENTS";
